import os
from agents.voice_keeper import rewrite_in_voice
from agents.publisher import open_pr

def fill(tpl: str, ctx: dict) -> str:
    for k,v in ctx.items():
        tpl = tpl.replace("${"+k+"}", v or "")
    return tpl

def main(title="AI adoption pitfalls in enterprises",
         out="site/docs/blog/ai-adoption-pitfalls.md"):
    os.makedirs(os.path.dirname(out), exist_ok=True)
    tpl = open("prompts/blog_fnf.md","r",encoding="utf-8").read()
    draft = fill(tpl, {
        "TITLE": title,
        "EVIDENCE": "- Change is harder than code\n- Incentives beat architecture\n- Start narrow, measure relentlessly"
    })
    final = rewrite_in_voice(draft)
    open(out,"w",encoding="utf-8").write(final)
    print(f"Wrote {out}")
    open_pr(out, final, title=f"Draft (blog): {title}", body="Generated by ECE")

if __name__=="__main__":
    main()
